language: perl
perl:
  - "5.28"
  - "5.18"
  - "5.26"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18.1-thr"
  - "5.20"
  - "5.22"
  - "5.24"
  - "blead"

os:
  - linux
  # Don't include OSX in the list here as we'd have to exclude it for most builds again
  #- osx

matrix:
  # Add one job for testing OSX
  include:
    - perl: "5.28"
      os: "osx"

  allow_failures:
    - perl: blead

sudo: required

dist: trusty
addons:
  apt:
    update: true
    packages:
      - freeglut3-dev
      - xutils-dev
      - libxi-dev
      - libxxf86vm-dev
      - x11proto-xf86vidmode-dev
      - mesa-utils
      - xvfb
      - libgl1-mesa-dri
      - libglapi-mesa
      - libosmesa6
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then grep -v blank /etc/fonts/fonts.conf | sudo tee /etc/fonts/fonts.conf; fi
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  # Install perlbrew the hard way, on OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade; brew install perl libpng freeglut --universal; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pkg-config libpng --cflags; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then \curl -L http://install.perlbrew.pl | bash; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then source ~/perl5/perlbrew/etc/bashrc; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then export PATH=$HOME/perl5/perlbrew/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then echo $TRAVIS_PERL_VERSION; fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then perlbrew install perl-$TRAVIS_PERL_VERSION; perlbrew use perl-$TRAVIS_PERL_VERSION; perlbrew install-cpanm; fi
  #
  # Install local::lib
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L http://cpanmin.us | perl - --notest --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib); fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L http://cpanmin.us | perl - --notest App::cpanminus; fi
  - export SPLIT_BUILD=0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ~/travis-perl-helpers/init; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then build-perl; fi
  - perl -V
  - cd $TRAVIS_BUILD_DIR

install:
  - cd $TRAVIS_BUILD_DIR
  - pwd
  # Initialize local::lib on OSX, a second time as this is a new shell session
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib); fi
  - cpanm --notest ExtUtils::MakeMaker~6.68
  - cpanm --notest Prima
  - cpanm --verbose --notest --installdeps .

script:
  - cd $TRAVIS_BUILD_DIR
  - perl Makefile.PL && make
  - prove -blv t/

branches:
  except:
    - /^wip\//
    - /^blocked/
#notifications:
#  email: false
#  irc:
#    channels:
#      - "irc.perl.org#moo-smoke"
#    template:
#      - "%{repository}#%{build_number} %{branch} by %{author}: %{message} (%{build_url})"
#    on_success: change
#    on_failure: always
#    skip_join: true
